/*
 * POSEIDON: an agent-based model of fisheries
 * Copyright (c) 2024-2025, University of Oxford.
 *
 * University of Oxford means the Chancellor, Masters and Scholars of the
 * University of Oxford, having an administrative office at Wellington
 * Square, Oxford OX1 2JD, UK.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This source file was generated by the Gradle 'init' task
 */
package uk.ac.ox.poseidon.core;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.Getter;
import sim.engine.SimState;
import sim.engine.Steppable;
import uk.ac.ox.poseidon.core.events.EventManager;
import uk.ac.ox.poseidon.core.events.SimpleEventManager;
import uk.ac.ox.poseidon.core.schedule.TemporalSchedule;

import java.io.Serial;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.time.temporal.TemporalAmount;
import java.util.*;
import java.util.stream.Stream;

import static com.google.common.base.Preconditions.checkNotNull;
import static com.google.common.collect.ImmutableSet.toImmutableSet;

@Getter
public class Simulation extends SimState {

    @Serial private static final long serialVersionUID = -8162246985852120341L;
    private final EventManager eventManager = new SimpleEventManager();
    private final TemporalSchedule temporalSchedule;
    private final UUID id;
    private final List<Steppable> finalProcesses = new ArrayList<>();
    private boolean started = false;
    List<?> components;

    @SuppressFBWarnings("EI_EXPOSE_REP2")
    Simulation(
        final long seed,
        final TemporalSchedule schedule,
        final UUID simulationId
    ) {
        super(seed, schedule);
        this.temporalSchedule = checkNotNull(schedule);
        this.id = simulationId;
    }

    @Override
    public void start() {
        if (started) throw new IllegalStateException("Simulation already started.");
        super.start();
        started = true;
    }

    public void addFinalProcess(final Steppable process) {
        finalProcesses.add(process);
    }

    public void addFinalProcess(final Runnable process) {
        finalProcesses.add(simState -> process.run());
    }

    @Override
    public void finish() {
        finalProcesses.forEach(process -> process.step(this));
        super.finish();
    }

    @Override
    public final int hashCode() {
        return super.hashCode();
    }

    @Override
    public final boolean equals(final Object obj) {
        return super.equals(obj);
    }

    private <T> Stream<T> getComponents(
        final Collection<?> component,
        final Class<T> componentClass
    ) {
        return component
            .stream()
            .flatMap(o ->
                o instanceof final Collection<?> c
                    ? getComponents(c, componentClass)
                    : Stream.of(o)
            )
            .filter(componentClass::isInstance)
            .map(componentClass::cast);
    }

    public <T> Set<T> getComponents(final Class<T> componentClass) {
        final Set<T> components =
            getComponents(this.components, componentClass).collect(toImmutableSet());
        if (components.isEmpty()) {
            throw new NoSuchElementException(
                "No components of class %s found in simulation.".formatted(componentClass.getName())
            );
        }
        return components;
    }

    public <T> T getComponent(
        final Class<T> componentClass
    ) {
        final Set<T> components = getComponents(componentClass);
        if (components.size() > 1) {
            throw new IllegalStateException(
                "More than one component of class " +
                    componentClass.getName() +
                    " found in simulation."
            );
        }
        return components.iterator().next();
    }

    public static void log(
        final System.Logger logger,
        final System.Logger.Level level,
        final SimState simState,
        final String format,
        final Object... args
    ) {
        logger.log(
            level,
            () -> {
                final Simulation simulation = (Simulation) simState;
                return simulation.getId() +
                    " [" + ((TemporalSchedule) simState.schedule).getTimestamp() + "] " +
                    MessageFormat.format(format, args);
            }
        );
    }

    public void step() {
        schedule.step(this);
    }

    public void stepFor(
        final TemporalAmount temporalAmount
    ) {
        temporalSchedule.stepFor(this, temporalAmount);
    }

    public void stepUntil(
        final SimState simState,
        final LocalDateTime dateTime
    ) {
        temporalSchedule.stepUntil(this, dateTime);
    }

}
