Prototype:
  biologyInitializer:
    Well-Mixed:
      capacityRatioSecondToFirst: '0.2'
      differentialPercentageToMove: '0.001'
      firstSpeciesCapacity: '5000.0'
      percentageLimitOnDailyMovement: '0.01'
      steepness: 0.7
  departingStrategy:
    Fixed Rest:
      hoursBetweenEachDeparture: '12.0'
  destinationStrategy:
    Imitator-Explorator:
      ignoreEdgeDirection: true
      probability:
        Adaptive Probability:
          explorationProbability: '0.8'
          explorationProbabilityMinimum: '0.01'
          imitationProbability: '1.0'
          incrementMultiplier: '0.02'
      stepSize: uniform 1.0 10.0
  engineWeight: normal 100.0 10.0
  fishers: 300
  fishingStrategy:
    Until Full With Day Limit:
      daysAtSea: '5.0'
  fuelTankSize: '100000.0'
  gasPricePerLiter: '0.01'
  gear:
    Random Catchability:
      meanCatchabilityFirstSpecies: '0.01'
      meanCatchabilityOtherSpecies: '0.01'
      standardDeviationCatchabilityFirstSpecies: '0.0'
      standardDeviationCatchabilityOtherSpecies: '0.0'
      trawlSpeed: '5.0'
  habitatInitializer: All Sand
  holdSize: '100.0'
  literPerKilometer: '10.0'
  mapInitializer:
    Simple Map:
      cellSizeInKilometers: '10.0'
      coastalRoughness: '0'
      depthSmoothing: '1000000.0'
      height: '50.0'
      width: '50.0'
  mapMakerDedicatedRandomSeed: 0
  market:
    Fixed Price Market:
      marketPrice: '10.0'
  networkBuilder:
    Equal Out Degree:
      degree: 2
  ports: 1
  portPositionX: 40
  portPositionY: 25
  regulation: MPA Only
  speedInKmh: '5.0'
  startingMPAs: [
    ]
  usePredictors: false
  weatherInitializer:
    Constant Weather:
      temperature: '30.0'
      windOrientation: '0.0'
      windSpeed: '0.0'
  weatherStrategy: Ignore Weather
