# number of bins
number_of_bins = 100
# meristics made up (assume meters)
L_zero = 10
L_inf = 113
max_age=40 #years
K=0.364
Mortality<-0.1/365
time_step_in_days = 1 #arbitrary


##I am assuming bins are equally spaced
#length_at_bin = L_zero + (L_inf-L_zero)*(0:((number_of_bins-1))/(number_of_bins-1))
##length_at_bin : 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

# #I am assuming bins are equally spaced IN TIME
# #this generates a constant graduation %
# time_per_bin<- seq(from=0,to=max_age,length.out = number_of_bins)
# length_at_bin = von_bert(time_per_bin,K,L_inf,L_zero)

# this is the different lengths generated by Peter's model
CV <- 0.1
factor1<-1.5
# #this is just the solution to the lfy discrete time difference model
# #from Peter's
deltaL<-factor1*2*L_zero*CV^2*(1+factor1*2*CV^2)^(0:(number_of_bins-1))
length_at_bin<-cumsum(deltaL)

# #this is how the space is split: the box cars are not all of the same size
# ggplot()+
#   geom_vline(xintercept=length_at_bin)
# # you can see that its difference is also exponential
# ggplot()+
#   geom_step(aes(x=2:number_of_bins,y=diff(length_at_bin)))
# 

# growth rate at bin (this is von bertalanffy)
growth_at_bin = K* (L_inf - length_at_bin)
growth_at_bin[growth_at_bin<0]<-0
#now this is really the derivative of yearly growth. 
#We want to turn it into growth over a period of days (assuming every year is 365 days)
# get differential
delta_t= time_step_in_days / 365
# scale growth to be at time step
growth_at_bin = growth_at_bin * delta_t




#distance in length between each bin (this is just 0.5m for all bins since we made them equi-distant)
length_between_bin<-c(diff(length_at_bin),1)  #the last one is no growth, any number but 0 will do
# graduating proportion each time step;
# that is how many fish move from one bin to the next each time step (5 days)
graduating_proportion<- growth_at_bin/length_between_bin



#method that actually simulate one time step
simulate_time_step<-function(current_distribution,graduation_proportion,
                             Mortality){
  #start from the oldest (to avoid fish aging twice in a row)
  for(i in (length(current_distribution)-1):1)
  {
    current_distribution[i]<- (1-Mortality)*current_distribution[i]
    #how many people graduates
    graduate<- (
      current_distribution[i] *graduation_proportion[i]
    )
    current_distribution[i+1]<-  current_distribution[i+1]  + graduate
    current_distribution[i]<- current_distribution[i] - graduate
  }
  return(current_distribution)
}
#now let's simulate
#initially arbitrarilly there are 10000 recruits
recruits<-10000
initial_distribution<-  c(recruits,rep.int(0,number_of_bins-1))
current_distribution<- initial_distribution

for(i in 1:100)
{
  current_distribution<-simulate_time_step(current_distribution,
                                           graduating_proportion,
                                           0)
}
paste(current_distribution,collapse=",")

