/*
 *  POSEIDON, an agent-based model of fisheries
 *  Copyright (C) 2020  CoHESyS Lab cohesys.lab@gmail.com
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package uk.ac.ox.oxfish.fisher.purseseiner.samplers;

import com.google.common.primitives.ImmutableDoubleArray;
import ec.util.MersenneTwisterFast;
import uk.ac.ox.oxfish.biology.LocalBiology;

import java.util.Collection;
import java.util.function.UnaryOperator;

import static com.google.common.collect.ImmutableList.toImmutableList;

/**
 * TODO.
 *
 * @param <B> The type of local biology generated by the sampler.
 */
@SuppressWarnings("UnstableApiUsage")
public abstract class CatchSampler<B extends LocalBiology> implements UnaryOperator<B> {

    private final ConditionalSampler<ImmutableDoubleArray> sampler;

    CatchSampler(
        final Collection<Collection<Double>> sample,
        final MersenneTwisterFast rng
    ) {
        this.sampler = new ConditionalSampler<>(
            sample.stream().map(ImmutableDoubleArray::copyOf).collect(toImmutableList()),
            rng
        );
    }

    public ImmutableDoubleArray next(final B sourceBiology) {
        return sampler.next(catchArray -> test(sourceBiology, catchArray));
    }

    abstract boolean test(B sourceBiology, ImmutableDoubleArray catchArray);

    /**
     * forces the sampler to look at the whole original data-set again
     */
    public void reset() {
        this.sampler.resetQueue();
    }

}
