/*
 * POSEIDON: an agent-based model of fisheries
 * Copyright (c) 2024 CoHESyS Lab cohesys.lab@gmail.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package uk.ac.ox.poseidon.agents.behaviours;

import uk.ac.ox.poseidon.agents.vessels.VesselScopeFactory;

/**
 * The main purpose of this class is to make it clear that behaviour factories should have vessel
 * scope. It also serves as a useful marker class to find all available behaviours.
 *
 * @param <B> the type of behaviour generated by this factory
 */
public abstract class BehaviourFactory<B extends Behaviour>
    extends VesselScopeFactory<B> {
}
